### PR TITLE
fix: audit logging

### LINKED ISSUE #491: Organization trees are not included in the Audit Log
Our audit log middleware intercepts API requests and logs the details of a request if its URL matches certain regexes.

https://github.com/Greenstand/treetracker-admin/blob/master/server/src/js/Audit.js#L93
```javascript
    } else if (/.*\/api\/trees\/\d+/.test(url)) {
```
This currently catches patches on `/api/trees/` but misses patches on trees associated with organizations (`/api/organization/{org_id}/trees/`).

It should catch all tree patches.

### LINKED ISSUE #492: Audit logging is not working
The process that writes logins and tree verifications to the `audit` table is failing for both actions.
- For logins, we're always returning code 401, even when login is successful.
- For tree verification actions, we are attempting to extract a user ID from the request that is not present.

### PR DESCRIPTION
**Pull request by luacmartins**
Should close #492

### CODE REVIEW

File: server/src/js/Audit.js [hunk 1]
```diff
@@ -95,7 +96,8 @@ class Audit {
       //assert(req.method, req.method);
       //assert(req.user);
       //assert(req.user.id);
-      operator = req.user.id;
+      operator = JSON.parse(req.headers.user)
```
Comment (dadiorchen) [inline server/src/js/Audit.js]: I doubt this is the correct way to do so, @luacmartins your idea is to pass in the user info directly from client right? I think you don't need to do so, and this might also be unsafe. 
The idea is: parse the auth token from client, get the user info, inject into the req, and get it in the audit middleware, then put into the DB

**Review by dadiorchen — CHANGES_REQUESTED** [review]

**Comment by luacmartins** [comment]
Thanks for the input @dadiorchen! Hopefully this solves the issue.

**Review by nmcharlton — APPROVED** [review]
Looks good to me. Thanks @luacmartins!
