### PR TITLE
fix: bug

### LINKED ISSUE #420: Fix species table not scrollable and no-jumping-to-the-start when selecting rows per page

### PR DESCRIPTION
**Pull request by elfiyang16**
resolve #420

Oct-02-2020 09-47-16

### CODE REVIEW

File: client/src/components/SpeciesTable.js [hunk 1]
```diff
@@ -28,6 +28,8 @@ import { withStyles } from '@material-ui/core/styles'
 
 const styles = (theme) => ({
   box: {
+    width: "80%",
```
Comment (nmcharlton) [inline client/src/components/SpeciesTable.js]: This looks a bit odd - there's a gap to the right of the scroll bar.

**Review by nmcharlton — CHANGES_REQUESTED** [review]
Can we make the contents scroll and keep the menu fixed on the left?
